const {test}=require('node:test')
const assert=require('node:assert/strict')
const fs=require('node:fs/promises')
const path=require('node:path')
const {pathToFileURL}=require('node:url')
const ts=require('typescript')
const React=require('react')
const {renderToStaticMarkup}=require('react-dom/server')

test('chat renders fenced SQL and plain code blocks, inline code, GFM tables and safe Markdown',async(t)=>{
  const root=path.resolve(__dirname,'..')
  const directory=await fs.mkdtemp(path.join(root,'out','markdown-test-'))
  t.after(async()=>{assert.ok(path.resolve(directory).startsWith(path.join(root,'out')+path.sep));await fs.rm(directory,{recursive:true,force:true})})
  const source=await fs.readFile(path.join(root,'src/renderer/src/components/ai/ChatMarkdown.tsx'),'utf8')
  const compiled=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText
  const file=path.join(directory,'ChatMarkdown.mjs');await fs.writeFile(file,compiled)
  const {default:ChatMarkdown}=await import(pathToFileURL(file).href)
  const text='**SQL preview**\n\n```sql\nBEGIN;\nUPDATE games\n  SET banner = \'image.png\';\nCOMMIT;\n```\n\nUse `game.id`.\n\n```\nplain <code>\n```\n\n| Name | Score |\n| --- | --- |\n| Median | 5 |\n\n<script>alert(1)</script>\n\n[bad](javascript:alert(1))'
  const html=renderToStaticMarkup(React.createElement(ChatMarkdown,{text}))
  assert.equal((html.match(/<pre /g)||[]).length,2)
  assert.equal((html.match(/aria-label="Copy code"/g)||[]).length,2)
  assert.ok(html.includes('BEGIN;\nUPDATE games\n  SET banner'))
  assert.ok(html.includes('plain &lt;code&gt;'))
  assert.ok(html.includes('<strong>SQL preview</strong>'))
  assert.ok(html.includes('game.id</code>'))
  assert.ok(html.includes('<table '))
  assert.ok(!html.includes('```'))
  assert.ok(!html.includes('<script>'))
  assert.ok(!html.includes('href="javascript:'))
})
